=== Ronnie74/corevoikko/data/words/wordlist.dtd
<!-- The root element of a word list -->
<!ELEMENT wordlist (word*)>
<!ATTLIST wordlist
          xml:lang CDATA #IMPLIED>

<!-- A word, or a record containing many related words -->
<!ELEMENT word (forms, classes, inflection?, usage?, compounding?,
                derivation?, style?, application?,
                frequency?, info?)>
<!ATTLIST word
          id ID #REQUIRED>

<!-- The word classes for this word -->
<!ELEMENT classes (wclass+)>

<!-- Word class -->
<!ELEMENT wclass (#PCDATA)>

<!-- Information about word inflection -->
<!ELEMENT inflection (infclass*, vtype?, flag*)>

<!-- Inflection class of the word -->
<!ELEMENT infclass (#PCDATA)>
<!ATTLIST infclass
          type (current|historical) "current">

<!-- The vowel type of the word in inflections -->
<!ELEMENT vtype (#PCDATA)>

<!-- Information about the spelling of the words in this record -->
<!ELEMENT forms (form+)>

<!-- Possible spelling -->
<!ELEMENT form (#PCDATA)>

<!-- Usage field flags assiciated with this record -->
<!ELEMENT usage (flag*)>

<!-- Compounding flags assiciated with this record -->
<!ELEMENT compounding (flag*)>

<!-- Derivation flags assiciated with this record -->
<!ELEMENT derivation (flag*)>

<!-- Style flags assiciated with this record -->
<!ELEMENT style (flag*)>

<!-- Application specific flags assiciated with this record -->
<!ELEMENT application (flag*)>

<!-- A binary flag -->
<!ELEMENT flag (#PCDATA)>

<!-- Information about the word -->
<!ELEMENT info (description?, link?, comment?)>

<!-- Description of this word -->
<!ELEMENT description (#PCDATA)>

<!-- Link to an external resource explaining this word -->
<!ELEMENT link (#PCDATA)>

<!-- Comments about this record -->
<!ELEMENT comment (#PCDATA)>

<!-- Information about the usage frequency of this word -->
<!ELEMENT frequency (fclass?, flag*)>

<!-- Frequency class -->
<!ELEMENT fclass (#PCDATA)>

=== Ronnie74/corevoikko/data/words/fi_FI-example.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE wordlist SYSTEM "wordlist.dtd">
<wordlist xml:lang="fi">
<word id="w518168">
	<forms>
		<form>šamaani</form>
		<form>samaani</form>
		<form>shamaani</form>
	</forms>
	<classes>
		<wclass>substantiivi</wclass>
		<wclass>etunimi</wclass>
		<wclass>sukunimi</wclass>
		<wclass>paikannimi</wclass>
		<wclass>nimi</wclass>
		<wclass>adjektiivi</wclass>
		<wclass>verbi</wclass>
	</classes>
	<inflection>
		<infclass>paperi</infclass>
		<infclass type="historical">banaali</infclass>
		<vtype>a</vtype>
		<flag>ei_vertm</flag>
		<flag>ei_yks</flag>
		<flag>yt</flag>
		<flag>paikannimi_sisäpaikallissijat</flag>
		<flag>paikannimi_ulkopaikallissijat</flag>
	</inflection>
	<use>
		<flag>atk</flag>
		<flag>lääketiede</flag>
		<flag>luonnontiede</flag>
		<flag>kasvatustiede</flag>
	</use>
	<compounding>
		<flag>ei_ys</flag>
		<flag>ei_ysj</flag>
		<flag>ei_ysa</flag>
		<flag>ysj</flag>
	</compounding>
	<derivation>
		<flag>ei_lainen</flag>
		<flag>ei_mainen</flag>
		<flag>inen</flag>
		<flag>ei_inen</flag>
	</derivation>
	<style>
		<flag>murre</flag>
		<flag>vanhaa_kieltä</flag>
		<flag>sivistyssana</flag>
		<flag>vieraskielinen</flag>
		<flag>kielivirhe</flag>
	</style>
	<application>
		<flag>ei_voikko</flag>
		<flag>ei_sukija</flag>
	</application>
	<description>tietäjä</description>
	<frequency>
		<fclass>7</fclass>
		<flag>sekoittuu_yleisempään</flag>
	</frequency>
</word>
</wordlist>
